export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";
export const STORES_LOADING = "STORES_LOADING";
export const ADD_STORES = "ADD_STORES";
export const STORES_FAILED = "STORES_FAILED";